# apiVersion: autoscaling/v2beta2
# kind: HorizontalPodAutoscaler
# metadata:
#   annotations:
#     autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2020-04-08T13:18:49Z","reason":"SucceededGetScale","message":"the
#       HPA controller was able to get the target''s current scale"},{"type":"ScalingActive","status":"False","lastTransitionTime":"2020-04-08T13:18:49Z","reason":"FailedGetResourceMetric","message":"the
#       HPA was unable to compute the replica count: unable to get metrics for resource
#       cpu: unable to fetch metrics from resource metrics API: the server could not
#       find the requested resource (get pods.metrics.k8s.io)"}]'
#   creationTimestamp: "2020-04-08T13:18:34Z"
#   name: dev-vernemq
#   namespace: default
#   resourceVersion: "1495755"
#   selfLink: /apis/autoscaling/v2beta2/namespaces/default/horizontalpodautoscalers/dev-vernemq
#   uid: 72e79fdf-799b-11ea-8f80-02be91224c3a
# spec:
#   maxReplicas: 10
#   minReplicas: 3
#   scaleTargetRef:
#     apiVersion: apps/v2beta2
#     kind: StatefulSet
#     name: dev-vernemq
#   metrics:
#     - type: Resource
#       resource:
#         name: memory
#         target:
#           type: Utilization
#           averageUtilization: 60
# status:
#   currentReplicas: 3
#   desiredReplicas: 0


apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: dev-vernemq
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: dev-vernemq
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60